version: "3.4"

services:
    api:
        build: ./api
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./api/src:/app/src
        depends_on: 
            - mongodb
        environment:
            - NODE_ENV=development
            - MONGO_URI=mongodb://mongodb/smol
    mongodb:
        image: mongo:5
        ports:
            - 27017:27017
