version: "3.4"

services:
    app:
        image: node:12
        ports:
            - 3000:3000
        command: sh -c "npm install && npm run dev"
        working_dir: /app
        volumes:
            - .:/app
        environment:
            - NODE_ENV=production
            - MONGO_URI=mongo/smol
    mongo:
        image: mongo:4
        ports:
            - 27017:27017
